version: "3"

services:
  app:
    build:
      context: .
    container_name: web
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"

    environment:
      - DB_NAME=railway
      - DB_USER=postgres
      - DB_PASSWORD=dLbqOZRNYbgidLxJsliXGAcNEvTnsLgJ
      - DB_HOST=postgres.railway.internal
      - DB_PORT=5432
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:14-alpine
    container_name: db
    ports:
      - "5432:5432"

    environment:
      - POSTGRES_DB=your_db_name
      - POSTGRES_USER=your_db_user
      - POSTGRES_PASSWORD=your_db_password
    volumes:
      - postgres_data:/var/lib/postgresql/data

    networks:
      - app-network


volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
